### ISSUE TITLE
Fix map size on screen rotation

### ISSUE THREAD

**Issue by MaticDiba** [DZRJL/katasterjam-mobile#21]
When you switch from vertical to horizontal screen and then back, the map is not extended correctly.

**Comment by MaticDiba** [comment]
@jeancaffou did you maybe encounter this issue before?

**Comment by jeancaffou** [comment]
This bug used to be present on GoogleMaps as well, but they fixed it, but in ye olde days we did a workaround by listening to window resize events, so you can try it:
https://openlayers.org/en/latest/apidoc/module-ol_Map-Map.html#updateSize
https://quasar.dev/vue-components/resize-observer

```vue
<q-resize-observer @resize="onResize" />
```
```javascript
methods: {
  onResize() {
   mapRef.updateSize()
}

**Comment by MaticDiba** [comment]
Ha, nice. I was looking for some vue hooks to do the trick, but didn't find anything useful. Didn't think quasar will offer something :)

Thanks
