### ISSUE TITLE
Build failed when merging #33

### ISSUE THREAD

**Issue by jeancaffou** [DZRJL/katasterjam-mobile#35]
Build failed when merging
- https://github.com/DZRJL/katasterjam-mobile/pull/33

Did you forget to commit `package.json`?

See job:
- https://github.com/DZRJL/katasterjam-mobile/actions/runs/4686364667/jobs/8304369632

It can't find dexie lib

**Comment by MaticDiba** [comment]
I did :( installed it, then did undo because of some testing ... then forgot to add it again. but it stayed in modules locally ofc ...
