### ISSUE TITLE
Offline OSM/... tiles

### ISSUE THREAD

**Issue by jeancaffou** [DZRJL/katasterjam-mobile#38]
https://data.maptiler.com/downloads/planet/

https://stackoverflow.com/a/43816959

**Comment by jeancaffou** [comment]
If you have DOF rasters you can generate tile files in ArcGIS I think and then add them as static jpegs in the project and reference a local Tile URL in OpenLayers

**Comment by MaticDiba** [comment]
My plan was to enable users to store tiles for different areas (limited by size). Also users should be able to select tiles they want to store: OSM, Lidar, Ortophoto. I was playing around with it (a while ago) here: https://github.com/MaticDiba/katasterjam-mobile/pull/1
With this approach, you store them in indexeddb. I am also building service, that will be caching tiles so I offload original providers OSM, gov.si, ... 

Something like this
```
MobileApp --> KatasterTileServer --> [CacheReadThrough] --> OriginalMapServer
```

For areas of limited size, this should be loaded fairly fast.

**Comment by jeancaffou** [comment]
It depens on how much work (clicking and browsing) does the user need to do in order to cache the desired area in relation to how large the app bundle size would be to just cache all of Slovenian tiles (at least for one layer, for example topo map)

We'll see in practice.
